### ISSUE TITLE
Question - What is RAW?

### ISSUE THREAD

**Issue by aaron29th** [koolkdev/libertyv#2]
I know this is very old now and you may not remember but I was wondering what is the RAW format I noticed this
```
// Well, it isn't REALLY raw. We are rewriting it, so of the regular random-header, there are zeros, 
//but it is close enough, that information is random anyway
```
in ResourceEntry.cs and was wondering what you meant by that and what is done to the data that can be seen in a rpf with HxD to get to the RAW file you can export

**Comment by koolkdev** [comment]
See ResourceStreamCreator.cs
The first 0x10 bytes are skipped because they are random. RAW is just the data , without the important metadata of the resource that is exported in the header of RSC7. No good reason to export as RAW.

**Comment by aaron29th** [comment]
Ok I understand the skipping of the first 16 bytes but is raw decrypted or how has it been changed from the raw data thats in the rpf.

Context - open iv exports raw files so I am trying to find out how I can decrypt and decompress these RAW files

**Comment by aaron29th** [comment]
At the moment I can open the rpf file in HxD and find the file and decrypt and decompress it but if I extract it with liberty v as raw it is different. So I'm trying to find out what exactly is done to the data from the rpf to get to the RAW file so I can reverse it.

**Comment by koolkdev** [comment]
So it isn't related to this... here it was about raw undecrypted resources.

**Comment by aaron29th** [comment]
It is related to liberty v as open iv developers have clearly used parts of liberty v and they only allow you to export in liberty V's raw format which renders the files useless because I can't work out how the data in the rpf file is changed to form the data in the raw file

![image](https://user-images.githubusercontent.com/20888296/29129824-fa46b542-7d1f-11e7-9aaf-85c572bc3e37.png)

The left side shows the file in the rpf which can be decrypted and decompressed but the same file exported to the raw format (right side) is completely different

**Comment by koolkdev** [comment]
Oh, sorry, I was wrong. RAW in LibertyV was the file encrypted and compressed. It should be the same as in the RPF.
```
        public override void Write(Stream stream)
        {
            // 0x10 ignored bytes
            stream.Write(new byte[0x10], 0, 0x10);
            FileStreamCreator originalStream = this.TryGetOriginalFileStreamCreator();
            // optimization: Check if we have the data from the original file, and we don't need to encrypt and compress it again
            if (originalStream != null)
            {
                originalStream.WriteRaw(stream);
            }
```
As you can see, I just read from the RPF itself.

**Comment by aaron29th** [comment]
Ye I'm beyond confused because suddenly it started working perfectly and it is now identical to the rpf, I have no clue what the problem was but thanks for your help
